### ISSUE TITLE
Numbers size bug?

### ISSUE THREAD

**Issue by Justpg91** [Tercioo/Plater-Nameplates#80] opened 2021-01-03 17:49 UTC
Newest Version of Plater.

Sometimes i get a numbersize bug of my Dots you can see it in the screenshots below.

This is how it should look : https://gyazo.com/5082dd128440abfb73ae151cee63b627
And when the bug happen : https://gyazo.com/c7fb366b2a154a9b8969ae5a7082fe97

Maybe someone got a fix for it or a trick how to fix it. 

Greetz

**Comment by rwinders** [comment] 2021-01-03 23:13
Having the same issue https://github.com/Tercioo/Plater-Nameplates/issues/73

**Comment by cont1nuity** [comment] 2021-01-04 22:00
Duplicate of #73

**Closed by cont1nuity** 2021-01-04 22:00 UTC
