### ISSUE TITLE
Combo points display issue

### ISSUE THREAD

**Issue by CruelDrool** [Tercioo/Plater-Nameplates#55] opened 2020-01-08 07:41 UTC
**Game and Plater version**
Retail with version 8.2.5.283

**Describe the bug**
This just happens when playing normally as a rogue. I have no way of reproducing it consistently. In the screenshot I actually have 2 combo points. Don't know why Plater is displaying the 6th one.

![WoWScrnShot_010820_082855](https://user-images.githubusercontent.com/17357859/71958912-bf9f7800-31f1-11ea-9cb1-6d04afd3cee4.jpg)

**Comment by Tercioo** [comment] 2020-01-08 13:45
Thanks for opening the issue, but can you describe the bug?

------ Original Message ------

**Comment by cont1nuity** [comment] 2020-01-08 16:42
I've discussed this issue on Discord with someone else a while back. Unfortunately, I cannot reproduce the issue...

@CruelDrool:
Can you please gather the following data:
- Any bugs from BugSack (exported to pastebin.com preferably)
- A list of addons you use
- Your profile exported to wago.io (or a link it is a shared one already)
- If possible any way to reproduce the issue

**Comment by cont1nuity** [comment] 2020-01-08 16:44
Just some notes on the side:
- the actual issue is the 6th active resource which should be inactive. This happened on WLs as well.
- There is currently no way for me to reproduce this issue...
- It is not Plater displaying this combo point, but the Blizzard resource frame (which is only moved by Plater).

**Comment by Tercioo** [comment] 2020-01-08 17:00
Got it, this resource issue is pretty old, I couldn't reproduce either.
I'll have some spare time next week, I'll see if I can make write resource monitors from scratch.

------ Original Message ------

**Comment by CruelDrool** [comment] 2020-01-08 17:03
> * It is not Plater displaying this combo point, but the Blizzard resource frame (which is only moved by Plater).

Oh, that could explain it.

> Got it, this resource issue is pretty old, I couldn't reproduce either. I'll have some spare time next week, I'll see if I can make write resource monitors from scratch.

So you don't need me to gather more data from my setup (addons and profile)?

**Comment by Tercioo** [comment] 2020-01-08 17:11
Yeah, you don't need, you may use the resource monitor from the Modding tab.

**Comment by CruelDrool** [comment] 2020-01-08 17:31
> Yeah, you don't need, you may use the resource monitor from the Modding tab.

Hmm, I'm unable to find that.

**Comment by cont1nuity** [comment] 2020-01-08 17:43
@CruelDrool not at this time, if I understood Tercioo correctly.
It could even be a blizzard bug.... You can use the mod below or the one delivered with Plater ("Combo Points [Plater]") as a replacement.

@Tercioo: I am a bit ahead of you: https://wago.io/2aTBu0L0_ :)

**Comment by CruelDrool** [comment] 2020-01-08 17:55
> > Yeah, you don't need, you may use the resource monitor from the Modding tab.
> 
> Hmm, I'm unable to find that.

Nevermind, I found it.

**Comment by cont1nuity** [comment] 2020-01-08 18:49
@CruelDrool the mod I linked above can be used as well, if you prefer a different style / look

**Comment by cont1nuity** [comment] 2022-04-05 22:34
Plater has its own resources implementation now. closing this as it is related to blizzard default resources.

**Closed by cont1nuity** 2022-04-05 22:34 UTC
