### ISSUE TITLE
LUA Errors 10.2.7

### ISSUE THREAD

**Issue by heftyweizen** [Tercioo/Plater-Nameplates#204] opened 2024-05-07 23:16 UTC
**Game and Plater version**
Which is the game version and Plater version you're using?
Plater-v578a-Retail - DF v530 - 10.2.7

**Describe the bug**
Fresh install of plater, importing a profile from Wago causes the options panel to pop up on every reload.  This was solved with:
 /run Plater.db.profile.reopoen_options_panel_on_tab = false

- Steps to Reproduce (what did you do to make the bug happen):

- Result (what happens when you follow the steps above):

- Expected (what you think the expected behavior would be when following the steps):

- When the bug started (a date, wow path release, details update, etc)?

- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*
```
17x [string "return _G['DetailsFrameworkTextEntryNumber1..."]:1: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
[string "=[C]"]: in function `SetJustifyV'
[string "return _G['DetailsFrameworkTextEntryNumber140']:SetJustifyV(...)"]:1: in main chunk
[string "=(tail call)"]: ?
[string "@Plater/libs/DF/textentry.lua"]:467: in function `?'
[string "@Plater/Plater_OptionsPanel.lua"]:13658: in function `OpenOptionsPanel'
[string "@Plater/Plater.lua"]:13404: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5422: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5074: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5110: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
(*temporary) = DetailsFrameworkTextEntryNumber140 {
 0 = <userdata>
 label = DetailsFrameworkTextEntryNumber140_Desc {
 }
 backdropInfo = <table> {
 }
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 MyObject = <table> {
 }
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Blizzard_SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 current_bordercolor = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Blizzard_SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
}
(*temporary) = "center"
```

```
17x [string "return _G['DetailsFrameworkTextEntryNumber2..."]:1: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
[string "=[C]"]: in function `SetJustifyV'
[string "return _G['DetailsFrameworkTextEntryNumber221']:SetJustifyV(...)"]:1: in main chunk
[string "=(tail call)"]: ?
[string "@Plater/libs/DF/textentry.lua"]:467: in function `SetAsSearchBox'
[string "@Plater/Plater_CastColorPanels.lua"]:1595: in function `CreateCastColorOptionsFrame'
[string "@Plater/Plater_OptionsPanel.lua"]:431: in function <Plater/Plater_OptionsPanel.lua:431>

Locals:
(*temporary) = DetailsFrameworkTextEntryNumber221 {
 0 = <userdata>
 label = DetailsFrameworkTextEntryNumber221_Desc {
 }
 backdropInfo = <table> {
 }
 OnBackdropLoaded = <function> defined @Blizzard_SharedXML/Backdrop.lua:152
 MyObject = <table> {
 }
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Blizzard_SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 current_bordercolor = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Blizzard_SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Blizzard_SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Blizzard_SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
}
(*temporary) = "center"

```

**Screenshots**
Post images of the bug if necessary.

**Other Information**
If necessary, add more info here.

**Comment by cont1nuity** [comment] 2024-05-07 23:24
Thanks, should be fixed with the latest release.

**Comment by joshjau** [comment] 2024-05-08 00:28
> Thanks, should be fixed with the latest release.

is this related to the fix you pushed? sorry on double up:

2x Details/Libs/DF/label.lua:159: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
[string "=[C]"]: in function `SetJustifyV'
[string "@Details/Libs/DF/label.lua"]:159: in function <Details/Libs/DF/label.lua:151>
[string "=(tail call)"]: ?
[string "@Plater/Plater_OptionsPanel.lua"]:1616: in function `?'
[string "@Plater/Plater_OptionsPanel.lua"]:1637: in function `OpenOptionsPanel'
[string "@Plater/Plater.lua"]:13403: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5422: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5368>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5074: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5073>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5110: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
(*temporary) = DetailsFrameworkLabelNumber673462 {
 0 = <userdata>
 MyObject = <table> {
 }
}
(*temporary) = "center"

**Comment by cont1nuity** [comment] 2024-05-08 06:09
> is this related to the fix you pushed? sorry on double up:

I cannot reproduce this. Which `/plater version` are you using?

**Closed** 2024-05-27 19:39 UTC
