### ISSUE TITLE
Cast - Glowing [P] OnShow error

### ISSUE THREAD

**Issue by joshbowman** [Tercioo/Plater-Nameplates#137] opened 2022-11-04 02:31 UTC
**Game and Plater version**
Which is the game version and Plater version you're using?
Full `/plater version` output please.
Plater-v537.1-Retail - DF v384 - 10.0.0

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Not certain what triggers it.  Seen it in combat on several characters now, but not consistently.

- Result (what happens when you follow the steps above):
Chat window gets spammed with OnShow error from this script (see screenshot)

**Screenshots**
Post images of the bug if necessary.
![image](https://user-images.githubusercontent.com/11521178/199872163-ae17eb94-f584-419d-8662-bfc126f41ebe.png)

**Comment by cont1nuity** [comment] 2022-11-04 08:26
Duplicate of #134

**Closed** 2022-11-04 08:26 UTC
