### ISSUE TITLE
Plater interfering with ElvUI Target/Focus Unit frames Alpha.

### ISSUE THREAD

**Issue by Skullcan** [Tercioo/Plater-Nameplates#148] opened 2022-12-12 14:16 UTC
**Game and Plater version**
Wow: 10.0.2.46924
Plater-v542-Retail - DF v402 - 10.0.2

**Describe the bug**
- Install ElvUI.
- Install Plater.
- Check if you have 'Fader' enabled on Target unit frames.
Result (what happens when you follow the steps above):
- The target unit frame won't fade when you are out of range.
Expected (what you think the expected behavior would be when following the steps):
- The target unit frame should fade when you are out of range.
When the bug started (a date, wow path release, details update, etc)?
Noticed it right after the first m0's I did, same week 10.0.0 hit.

**Additional information:**
If my target is a non-interactable NPC/Vendor the Fader works properly

**Screenshots**
Player marked and out of range
![image](https://user-images.githubusercontent.com/10976772/207066966-0568820b-6224-4eaf-a8f0-1b38395f4161.png)

Interactable NPC marked and out of range
![image](https://user-images.githubusercontent.com/10976772/207067160-e39f84f2-154a-4bf7-a355-55d4bab0b84e.png)

Non-interactable NPC marked and out of range
![image](https://user-images.githubusercontent.com/10976772/207067216-65f822c6-b341-44b1-b884-e0d81f266fa3.png)

**Other Information**
All the examples here are NPC's/Players but it's the same with Hostiles.
Party and Raid frames fader works.

**Comment by cont1nuity** [comment] 2022-12-12 14:31
To my knowledge this is caused by ElvUI using an outdated version of LibRangeCheck while Plater is using the latest one.
As a bandaid, you could copy one version of the lib to the other addon.
I see this on their side.

**Comment by Skullcan** [comment] 2022-12-12 14:52
> To my knowledge this is caused by ElvUI using an outdated version of LibRangeCheck while Plater is using the latest one. As a bandaid, you could copy one version of the lib to the other addon. I see this on their side.

Thanks for the fast reply!

Tried what you said.

- Copied Plater's LibRangeCheck-2.0 to ElvUI, didin't work, same bug.
- Copied ElvUI's LibRangeCheck-2.0 to Plater, and now it's working.

What do you suggest now? Should I make the same Issue report on their side?

**Comment by cont1nuity** [comment] 2022-12-12 15:02
Would not hurt to have their opinion.
I'll check other projects versions.

**Comment by cont1nuity** [comment] 2022-12-12 15:05
Maybe I'll switch over to another version and see how that behaves.

**Comment by cont1nuity** [comment] 2022-12-13 11:37
Should be resolved with the latest alpha.

**Closed by cont1nuity** 2022-12-13 11:37 UTC
